language: java
jdk: oraclejdk8
env:
  global:
    - secure: "C3AtczJyvuLGfuDAjo1gq9/pLDN0bGfJQ5pL7ms8jZqzPfXh7jBPDXYtKt5qT9/mAQszbY4NO/pzeeLHluzaJa0z1vzKlpiwUKYLvJD0FS+HABsZTlN/EGI88JKItDvbHFMdzOODek9rpobrAkntiXVaPng9J+MXkm23nhR6zg4ukRK2pBTJelVl+lFKOUDLRxeQZgGgG9gbNahfTdmJHV/5II1fdOdABkDm9jue4ja9UWXYI0sPUQ0mYtlAjFOS+TNIYxqk8+DbKQ+juRfLtnVgh3kCzmslb8jZkPzWvmuu5yrrI1f7WIcWJVn5vMNCyqysx573d65W38w/Tp6ckXdECTmnkb2E7OwVX7bcchXCIjV/rGuP8RW7chuNG82h3h5ssEzkO1AHH4yRaBG8btL+wLexxv5hjqYS4znfWO+sjUwrCScmB3lvjflqoTROxHf5ZziIOBOnuAoJljYjcPOSwLXfbGRd47rMIYgT9iCoAGCD731oOsK7MDwOToFCqtKSh+e31W6v3SS8j+08dTtilec4CQz6dfIGFmee/+aVODaKr/BzaaYRqyEu7K2tTuqqJb1AghPQiN4jwh01ROfgEEGX+SrRC1jEP8hAGuo7JBJIen78/r6TtXde6xxlj1jQo8pW7xC8p9vcseaKb3LUmWjvqYcewdTJLRYyR+k="
    - secure: "u4ql5HFGDWCuXiJDubtwm83phKjRvgzaHVNuBIgHwnBz1oRClDQ24qvoaAoDp9ffYcw0LB2o2HHzhMhpIohizuzLVX3qwa43ClkC4NreaAVYZaLAHWoSeCt4CVp8pcZgfzjy9eIpc1NQdfOuRLknIC4V8Bvuln7wMo3WCnze0UO5U7mp61x/CYwuKCjh7jyqcKfKwYr864P5jTbu7jaQuF55vxCCxDTrkcoGl4a5w7bZD9BemePci9Ln8ibDqMWsbXriHnFqv4xxxOaD2d+IXAT8LHknJiaab5vqlPA3GZsPDaV9Q6iLK1nlU2YEs4EkMNLjKbPvQc6JDVo+sBcsSeXAYnZYFzSrlCSo1+bp8sLI1ezFmzd3nys0L1FhbF5iUbMruKKif6nqGLeJk2D3z8dU9rRkhPqzOTNHGDgZyosJYipW8A/HF0kn1XsTl2UjES3WSU9uRZL5t2/hX/m0J3w7JWi/6TT+Xt/iU7rWK860GYo/Ck+d0iIc3ThgA4RlIQ+RXRqLSDuXqV5xkDqtKrijPvrh9T+FhXRL+Zi7Fb4PNpSa4hkKLDgEpXnNv4Q21agL6pKwNP5vp5w0RI7Jwdmsvhn8J3bMisL8RvCz0A82iXnxGWdR1skXKlaNob73ga4DvGhawDlA2eub4or3KBIB9NUk03+m54Q2ZdejAG8="
script: mvn package -Dmaven.javadoc.skip=true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssh-client sshpass
after_success:
  - chmod a+x scripts/upload-so6rfc.sh
  - ./scripts/upload-so6rfc.sh
